### ISSUE TITLE
Broken After 7.6+ update

### ISSUE THREAD

**Issue by jeffstempel** [TimGeyssens/LookWhosEditingToo#12]
It appears that LWET no longer works as of the newest 7.6 update. My main app has not updated on the LWET tab and no longer displays messages when users are on the same page.

I tried a brand new 7.6.6 app and was unable to get the tab to load or the message to display.

However, I reloaded a 7.4.3 app I have and was able to get the tab to load, display who's on what page, and get a message when I had a user on the same page.

**Comment by Riadhoq** [comment]
In case you still looking for a fix, we fixed it. Now it supports Umbraco v7.6 and higher.
